### ISSUE TITLE
ConsoleColor.Green in variabele

### ISSUE THREAD

**Issue by MichWouters** [Thalittleboy/Assignments-learningFevor#1]
https://github.com/Thalittleboy/Assignments-learningFevor/blob/031fbdb303dac51bf7e20bb0db7b73fbac95b582/ASCII%20Art%20and%20Colors/Program.cs#L13

ConsoleColor.Green wordt steeds opnieuw gebruikt.
Steek dit in een variabele (Mag even var zijn) zodat je deze variabele kunt hergebruiken  en de kleur makkelijk kunt aanpassen.

**Comment by Thalittleboy** [comment]
Aangepast
