### ISSUE TITLE
Kan char worden

### ISSUE THREAD

**Issue by MichWouters** [Thalittleboy/Assignments-learningFevor#12]
https://github.com/Thalittleboy/Assignments-learningFevor/blob/04f172bf06bd56d9797b4d8837634096ad18f178/Het%20Orakeltje%20van%20Delphi/Program.cs#L14

https://github.com/Thalittleboy/Assignments-learningFevor/blob/04f172bf06bd56d9797b4d8837634096ad18f178/Het%20Orakeltje%20van%20Delphi/Program.cs#L23

https://github.com/Thalittleboy/Assignments-learningFevor/blob/04f172bf06bd56d9797b4d8837634096ad18f178/Het%20Orakeltje%20van%20Delphi/Program.cs#L27

Deze string zal maar 1 karakter bevatten. Maak hier een char van.

**Comment by Thalittleboy** [comment]
aangepast
