### ISSUE TITLE
Verkeerd gebruik van doubles

### ISSUE THREAD

**Issue by MichWouters** [Thalittleboy/Assignments-learningFevor#15]
https://github.com/Thalittleboy/Assignments-learningFevor/blob/04f172bf06bd56d9797b4d8837634096ad18f178/Simple%20Maths/Program.cs#L17
https://github.com/Thalittleboy/Assignments-learningFevor/blob/04f172bf06bd56d9797b4d8837634096ad18f178/Simple%20Maths/Program.cs#L21

Waarom niet gewoon 6.0, 7.0 etc. gebruiken? Dat bespaart een conversie

**Comment by Thalittleboy** [comment]
De opdracht heeft mij waardes gegeven, ik kan toch niet zomaar de originele waardes aanpassen?
