### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by MichWouters** [Thalittleboy/Assignments-learningFevor#16]
https://github.com/Thalittleboy/Assignments-learningFevor/blob/6025a7b3400a6c8d030342680966e085f3d25fc1/Gewicht%20in%20space/Program.cs#L26-L37

Tip: Laat Visual Studio voor je werken. 
Klik op een plus in concatenated string -> Klik op icoontje dat links vertschijnt -> Convert To Interpolated -> Fix in File.

**Comment by MichWouters** [comment]
Denk aan genoeg whitespacing.
Via deze layout is onmiddelijk duidelijk waar kleuren beginnen en stoppen:
`Console.WriteLine("Uw gewicht in kg?");
            double gewichtOpAarde = Convert.ToDouble(Console.ReadLine());

            Console.WriteLine("\nGewicht op Aarde: " + gewichtOpAarde + " kg.");
            Console.WriteLine("Gewicht op Mercurius: " + gewichtOpAarde * .38 + " kg.");
            Console.WriteLine("Gewicht op Venus: " + gewichtOpAarde * .91 + " kg.");
            Console.WriteLine("Gewicht op Mars: " + gewichtOpAarde * .38 + " kg.");
            
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("Gewicht op Jupiter: " + gewichtOpAarde * 2.34 + " kg.");
            Console.ResetColor();

            Console.WriteLine("Gewicht op Saturnus: " + gewichtOpAarde * 1.06 + " kg.");
            Console.WriteLine("Gewicht op Uranus: " + gewichtOpAarde * .92 + " kg.");
            Console.WriteLine("Gewicht op Neptunus: " + gewichtOpAarde * 1.19 + " kg.");
            
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Gewicht op Pluto: " + gewichtOpAarde * .06 + " kg.");
            Console.ResetColor();

            Console.ReadLine();`

**Comment by Thalittleboy** [comment]
> https://github.com/Thalittleboy/Assignments-learningFevor/blob/6025a7b3400a6c8d030342680966e085f3d25fc1/Gewicht%20in%20space/Program.cs#L26-L37
> 
> Tip: Laat Visual Studio voor je werken. Klik op een plus in concatenated string -> Klik op icoontje dat links vertschijnt -> Convert To Interpolated -> Fix in File.

Ik zie niet wat je zegt.
