### ISSUE TITLE
Lijntje whitespace voor en na if statements

### ISSUE THREAD

**Issue by MichWouters** [Thalittleboy/Assignments-learningFevor#6]
https://github.com/Thalittleboy/Assignments-learningFevor/blob/031fbdb303dac51bf7e20bb0db7b73fbac95b582/BMI/Program.cs#L27

**Comment by Thalittleboy** [comment]
Als in dit moet ik toevoegen?

**Comment by Thalittleboy** [comment]
Aangepast
