### ISSUE TITLE
Bad Practice

### ISSUE THREAD

**Issue by MichWouters** [Thalittleboy/Assignments-learningFevor#9]
https://github.com/Thalittleboy/Assignments-learningFevor/blob/04f172bf06bd56d9797b4d8837634096ad18f178/Seizoenen/Program.cs#L17

Het is een goede practice om de 'fallback value', de waarde die gegeven wordt als geen enkele andere waarde waar is, helemaal vooraan te plaatsen. Over het waarom later meer.

**Comment by Thalittleboy** [comment]
Aangepast
